/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package to.pkgdo.listms.view;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.Timer;
import javax.swing.UIManager;
import to.pkgdo.listms.database.DBConnection;

/**
 *
 * @author USER
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        showDueTasksMessage();
        jDesktopPane1.removeAll();
        playBackgroundMusic();
        Dashboard dash = new Dashboard();
        jDesktopPane1.add(dash).setVisible(true);
        Timer timer = new Timer(1000, new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        // Call the curDateTime() method to update the label
        curDateTime();
        
        
    }
});

// Start the Timer
timer.start();
        


       // showDueTasksMessage();
    }
    
    
    private void playBackgroundMusic() {
    try {
        // Load the audio file
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(getClass().getResource("/Music/Microsoft Windows Vista Beta Shutdown Sound.wav"));

        // Create a clip to play the audio
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        //showDueTasksMessage();

        // Play the audio once
        clip.start();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    
    
    public void setUserData(String username, byte[] userPhoto) {
        lblusername.setText(username);
        lbluserphoto.setImagen(new ImageIcon(userPhoto));
    }
    
    
    public void curDateTime(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd    HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        lblDate.setText(dtf.format(now));
    }
    
    private void showDueTasksMessage() {
        JPanel messagePanel = new JPanel(new BorderLayout());
        
        // Customize the appearance of the panel with a modern design
        messagePanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Add some padding
        
        JLabel titleLabel = new JLabel("Tasks Due Today");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 16));
        messagePanel.add(titleLabel, BorderLayout.NORTH);

        JTextArea tasksTextArea = new JTextArea();
        tasksTextArea.setEditable(false);
        tasksTextArea.setWrapStyleWord(true);
        tasksTextArea.setLineWrap(true);
        
        // Query the database for tasks due today and populate the JTextArea
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT title FROM task WHERE dueDate = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setDate(1, new java.sql.Date(System.currentTimeMillis())); // Today's date
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                tasksTextArea.append("- " + rs.getString("title") + "\n");
            }
            
            rs.close();
            pst.close();
            //con.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        messagePanel.add(new JScrollPane(tasksTextArea), BorderLayout.CENTER);
        
        // Display the JOptionPane with the custom panel
        JOptionPane.showMessageDialog(this, messagePanel, "Due Tasks Today", JOptionPane.INFORMATION_MESSAGE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        rSButtonHover2 = new rojerusan.RSButtonHover();
        rSButtonHover3 = new rojerusan.RSButtonHover();
        rSButtonHover4 = new rojerusan.RSButtonHover();
        rSButtonHover5 = new rojerusan.RSButtonHover();
        panel1 = new java.awt.Panel();
        lbluserphoto = new rojerusan.RSPanelCircleImage();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        lblusername = new java.awt.Label();
        label3 = new java.awt.Label();
        jDesktopPane1 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(0, 0, 51));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonHover2.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        rSButtonHover2.setForeground(new java.awt.Color(0, 255, 255));
        rSButtonHover2.setText("HOME");
        rSButtonHover2.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover2.setColorText(new java.awt.Color(0, 255, 255));
        rSButtonHover2.setColorTextHover(new java.awt.Color(0, 255, 255));
        rSButtonHover2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rSButtonHover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover2ActionPerformed(evt);
            }
        });
        panel2.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        rSButtonHover3.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        rSButtonHover3.setForeground(new java.awt.Color(0, 255, 255));
        rSButtonHover3.setText("ADD TASK");
        rSButtonHover3.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover3.setColorText(new java.awt.Color(0, 255, 255));
        rSButtonHover3.setColorTextHover(new java.awt.Color(0, 255, 255));
        rSButtonHover3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rSButtonHover3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover3ActionPerformed(evt);
            }
        });
        panel2.add(rSButtonHover3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        rSButtonHover4.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        rSButtonHover4.setForeground(new java.awt.Color(0, 255, 255));
        rSButtonHover4.setText("TASK MANAGER");
        rSButtonHover4.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover4.setColorText(new java.awt.Color(0, 255, 255));
        rSButtonHover4.setColorTextHover(new java.awt.Color(0, 255, 255));
        rSButtonHover4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rSButtonHover4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover4ActionPerformed(evt);
            }
        });
        panel2.add(rSButtonHover4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        rSButtonHover5.setBackground(new java.awt.Color(102, 102, 102));
        rSButtonHover5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        rSButtonHover5.setForeground(new java.awt.Color(0, 255, 255));
        rSButtonHover5.setText("SEARCH TASK");
        rSButtonHover5.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover5.setColorText(new java.awt.Color(0, 255, 255));
        rSButtonHover5.setColorTextHover(new java.awt.Color(0, 255, 255));
        rSButtonHover5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rSButtonHover5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover5ActionPerformed(evt);
            }
        });
        panel2.add(rSButtonHover5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 220, 360));

        panel1.setBackground(new java.awt.Color(0, 0, 51));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbluserphoto.setBackground(new java.awt.Color(0, 0, 51));
        lbluserphoto.setColorBorde(new java.awt.Color(0, 255, 255));
        lbluserphoto.setColorFondo(new java.awt.Color(0, 51, 51));
        lbluserphoto.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-100 (1).png"))); // NOI18N

        javax.swing.GroupLayout lbluserphotoLayout = new javax.swing.GroupLayout(lbluserphoto);
        lbluserphoto.setLayout(lbluserphotoLayout);
        lbluserphotoLayout.setHorizontalGroup(
            lbluserphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );
        lbluserphotoLayout.setVerticalGroup(
            lbluserphotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        panel1.add(lbluserphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 101, 102));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonRectangle2.setForeground(new java.awt.Color(0, 255, 255));
        rSMaterialButtonRectangle2.setText("LOGOUT");
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        panel1.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 180, 40));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(102, 102, 102));
        rSMaterialButtonRectangle3.setForeground(new java.awt.Color(0, 255, 255));
        rSMaterialButtonRectangle3.setText("ACCOUNT SETTINGS");
        rSMaterialButtonRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle3ActionPerformed(evt);
            }
        });
        panel1.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 40));

        lblusername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblusername.setForeground(new java.awt.Color(0, 255, 255));
        lblusername.setText("1001");
        panel1.add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 255, 255));
        label3.setText("ADMIN : ");
        panel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 240));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 1070, 540));

        panel4.setBackground(new java.awt.Color(0, 0, 51));
        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 255, 255));
        label1.setText("TASK MANAGER");
        panel4.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 280, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-to-do-30.png"))); // NOI18N
        panel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 30, 30));

        lblDate.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 255, 255));
        lblDate.setText("2022.05.04   23:34:45");
        panel4.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jPanel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 1070, 50));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, 1070, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover2ActionPerformed
        jDesktopPane1.removeAll();
        Dashboard dash = new Dashboard();
        jDesktopPane1.add(dash).setVisible(true);
    }//GEN-LAST:event_rSButtonHover2ActionPerformed

    private void rSButtonHover3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover3ActionPerformed
       jDesktopPane1.removeAll();
        AddTask adt = new AddTask();
        jDesktopPane1.add(adt).setVisible(true);
    }//GEN-LAST:event_rSButtonHover3ActionPerformed

    private void rSButtonHover4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover4ActionPerformed
         jDesktopPane1.removeAll();
        TaskManager adt = new TaskManager();
        jDesktopPane1.add(adt).setVisible(true);
    }//GEN-LAST:event_rSButtonHover4ActionPerformed

    private void rSButtonHover5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover5ActionPerformed
       jDesktopPane1.removeAll();
        Search src = new Search();
        jDesktopPane1.add(src).setVisible(true);
    }//GEN-LAST:event_rSButtonHover5ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void rSMaterialButtonRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle3ActionPerformed
        jDesktopPane1.removeAll();
        AcoountSettings seting = new AcoountSettings();
        jDesktopPane1.add(seting).setVisible(true);
    }//GEN-LAST:event_rSMaterialButtonRectangle3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            UIManager.setLookAndFeel(new FlatMacDarkLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private javax.swing.JLabel lblDate;
    private java.awt.Label lblusername;
    private rojerusan.RSPanelCircleImage lbluserphoto;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel4;
    private rojerusan.RSButtonHover rSButtonHover2;
    private rojerusan.RSButtonHover rSButtonHover3;
    private rojerusan.RSButtonHover rSButtonHover4;
    private rojerusan.RSButtonHover rSButtonHover5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    // End of variables declaration//GEN-END:variables
}
